### ISSUE TITLE
Position saving and printing is not working properly.

### ISSUE THREAD

**Issue by shriharshtendulkar** [riyagori1203/RFI-Loc#1]
After identifying and selecting multiple intersections I clicked on the "Save Positions" button. The `output.txt` file has only the output from the last source selected `source 14`. 

`output.txt`
```
source 14 ['24', '25', '32', '43', '22', '42', '70', '8', '20', '41', '19', '40', '21', '16', '33', '54', '55', '35', '44', '51', '52', '5', '39', '49', '4', '50', '6', '10', '11', '69', '9', '18', '29', '56', '73', '26', '27']position: 597.97 14.85

```
The delay_ids get appended to the list without clearing.

The output on the terminal looks fine:
```
source 1 -> ['24', '25', '32', '43']
position: 374.57 , 248.19
source 2 -> ['22', '42', '70']
position: 704.27 , -1121.83
source 3 -> ['8', '20', '41']
position: 103.49 , 218.0
source 4 -> ['19', '40']
position: 82.25 , 202.55
source 5 -> ['21']
position: 117.0 , 239.23
source 6 -> ['16', '33', '54', '55']
position: 2212.03 , 3332.09
source 7 -> ['35', '44', '51', '52']
position: 3548.95 , 2856.45
source 8 -> ['5', '39', '49']
position: -963.04 , 1831.8
source 9 -> ['4', '50']
position: -984.5 , 1855.94
source 10 -> ['6']
position: -938.89 , 1826.43
source 11 -> ['10', '11', '69']
position: 548.87 , -1509.7
source 12 -> ['9', '18']
position: 521.07 , -1470.78
source 13 -> ['29', '56', '73']
position: -743.56 , 3704.59
source 14 -> ['26', '27']
position: 597.97 , 14.85
```

The expected behaviour is that the Save Positions Button will save all the previously identified sources in one shot. Not one at a time.
- [x] Add a variable/list that holds the existing intersections and delay_ids from mouse clicks.
- [x] Reconfigure `save_pos`  to save all of them in one go.
- [x] Open `output.txt` for overwriting not for appending.

**Comment by riyagori1203** [comment]
Yes this issue has been resolved, the software now saves the source and the position to a text file and the user can save it in the file of his/her choice.
The preview of the file is as follows after clicking "save positions"
[['source', 1, '->', ['31', '49', '50'], 'position:', 409.39, 1651.54], ['source', 2, '->', ['41'], 'position:', -85.53, 1661.54], ['source', 3, '->', ['27', '51', '52'], 'position:', 119.44, 2316.43], ['source', 4, '->', ['32', '54', '55'], 'position:', 579.36, 2541.39], ['source', 5, '->', ['13', '14', '15'], 'position:', 1024.29, 2061.47]]
We can work on formatting the output in a better way.
